### ISSUE TITLE
Actividad 3 Architec - Rodolfo NV

### ISSUE THREAD

**Issue by RodolfoNV** [SistemasTecTlaxiaco/actividad-3-practica-architect-RodolfoNV#1]
https://drive.google.com/file/d/1e5X_ndZrBJmTHyp1qFpDhaNmkXlsUrwM/view?usp=sharing

**Comment by AricelCastro** [comment]
Cumple con todo conforme a la rúbrica 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
